Import NumPy in Python

In [3]:
import numpy as np

NumPy Array Creation

In [12]:
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


In [13]:
arr2 = np.array([[1, 2, 3, 4, 5],[5 ,4 ,3 ,2 ,1]])
print(arr2)

[[1 2 3 4 5]
 [5 4 3 2 1]]


In [14]:
arr3 = np.array([[[1, 2, 3, 4, 5],[5 ,4 ,3 ,2 ,1],[2 ,3 ,1 ,4 ,5]],
[[1, 2, 3, 4, 5],[5 ,4 ,3 ,2 ,1],[2 ,3 ,1 ,4 ,5]]])
print(arr3)

[[[1 2 3 4 5]
  [5 4 3 2 1]
  [2 3 1 4 5]]

 [[1 2 3 4 5]
  [5 4 3 2 1]
  [2 3 1 4 5]]]


Check dimensions of an Numpy Array

In [16]:
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


NumPy Array shape Attribute

In [17]:
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

(5,)
(2, 5)
(2, 3, 5)


Check Data Type of a NumPy Array

In [18]:
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

int64
int64
int64


Check Size of Numpy array

In [19]:
print(arr1.size)
print(arr2.size)
print(arr3.size)

5
10
30


NumPy Array itemsize Attribute

In [20]:
print(arr1.itemsize)
print(arr2.itemsize)
print(arr3.itemsize)

8
8
8


Check Data Type of a NumPy Array

In [21]:
print(arr1.data)
print(arr2.data)
print(arr3.data)

Access Array Elements Using Index

In [23]:
array1 = np.array([1, 3, 5, 7, 9])
print(array1[0])
print(array1[2])
print(array1[4])

1
5
9


Modify Array Elements Using Index

In [24]:
array1[1]=10
print(array1)

[ 1 10  5  7  9]


2-D NumPy Array Indexing

In [25]:
array1 = np.array([[1, 3, 5, 7],
                       [9, 11, 13, 15],
                       [2, 4, 6, 8]])
element1 = array1[1, 3]
print("4th Element at 2nd Row:",element1)
element2 = array1[0, 1]
print("2nd Element at First Row:",element2)

4th Element at 2nd Row: 15
2nd Element at First Row: 3


NumPy Statistical Functions

In [26]:
array1 = np.array([1, 2, 3, 4, 5])
median = np.median(array1)
print(median)

3.0


Compute Mean Using NumPy

In [27]:
marks = np.array([76, 78, 81, 66, 85])
mean_marks = np.mean(marks)
print(mean_marks)

77.2


Standard Deviation of NumPy Array

In [28]:
marks = np.array([76, 78, 81, 66, 85])
std_marks = np.std(marks)
print(std_marks)

6.368673331236263


Numpy Percentile

In [29]:
marks = np.array([76, 78, 81, 66, 85])
std_marks = np.percentile(marks,50)
print(std_marks)

78.0


Numpy min

In [30]:
marks = np.array([76, 78, 81, 66, 85])
std_marks = np.min(marks)
print(std_marks)

66


Numpy max

In [31]:
marks = np.array([76, 78, 81, 66, 85])
std_marks = np.max(marks)
print(std_marks)

85
